### ISSUE TITLE
write analysis scripts for log data

### ISSUE THREAD

**Issue by santolucito** [Barnard-PL-Labs/SequencerLiveCoding#20]
start by analysis of the csc_workshop data.

Some key questions:

- What is the ratio of clickEvents to keyEvents
- What is the average time between successive clickEvents
- Which keys are being clicked (histogram)? Specifically, we are mostly seeing small edits (might be represented by a similar number of Backspace events to other keyEvents), or writing code from scratch (might be represented by a smaller relative number of Backspace events?)?

**Comment by takumh** [comment]
- ratio of click to key events resolved by function CountEvents
- average time between successive clickEvents resolved by function timeAnalysis
- analysis of keys clicked resolved by function keyAnalysis

**Comment by santolucito** [comment]
Closed by 0616568721

**Comment by santolucito** [comment]
Closed by e0616568721ce75420d99f06ca323a030ac276df

**Comment by takumh** [comment]
![KeyFreqTable](https://user-images.githubusercontent.com/84249146/148854083-21a33d87-9ba7-4204-bd72-65d32945cc53.png)

This key frequency table shows that the four frequently used keys are backspace, shift, arrow left and arrow right.  Backspace is the most used key, maybe people are not sure of the syntax and end up deleting a lot of the code they write? Perhaps tutorials on syntax would help. Interesting to note that numbers are not being used as much, maybe people need to know all the keys they can use on the tool and what they do.

**Comment by takumh** [comment]
![userEvents](https://user-images.githubusercontent.com/84249146/148854441-e4cc78ff-aeaa-4f29-b0e4-6b1f27ab2ed6.png)

Based on this pie chart, the majority of the users use both key and click functions on the tool, some use only click functions and a very small group uses only key functions.
