### ISSUE TITLE
Creating a Docker Container

### ISSUE THREAD

**Issue by nupurd89** [Barnard-PL-Labs/SequencerLiveCoding#30]
This week I started researching Docker and understanding how we could create a docker container that runs on Ubuntu 20.04 and contains the ltlsynth and tsltools binaries inside of it. Last week, we found out that we cannot just run the executable in a lambda because the lambda environment doesn’t have the most recent version of C. To fix this, we can try to use a docker container that runs on Ubuntu 20.04 (so it has the right version of C). I watched numerous tutorial videos understanding the objective and role of docker and then tried to create my own docker file with the specifications listed above. I am currently running into the following error: ERROR [6/6] RUN ./tslsynth "always assume {} always guarantee { [play <- noteG];}.

**Comment by santolucito** [comment]
Im pretty sure this issue belongs in the tsltools repo. please reopen there
